Django/Blog/Code/mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	# Navigate to post_list if no para
	# First para: url pattern
	# Second para: the view to open, the view is defined in views.py
	# name the url

	# First pattern doesn't pass para
	url(r'^$', views.post_list, name = 'post_list'),
	# Second gives one para
	url(r'^tag/(?P<tag_slug>[-\w]+)/$',views.post_list,name='post_list_by_tag'),

	# Navigate to detail if year+month+day+postinfo
	# Name of this url is 'post_detail'
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
	views.post_detail,
	name = 'post_detail'),
	
	url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
]

Django/Blog/Code/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

Django/Blog/Code/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

class PublishManager(models.Manager):
	def get_queryset(self):
		return super(PublishManager, self).get_queryset().filter(status = 'published')

# Create your models here.
class Post(models.Model):
	STATUS_CHOICES = (
		('draft','Draft'),
		('published', 'Published'),
	)

	title = models.CharField(max_length =250)
	slug = models.SlugField(max_length =250, unique_for_date = 'publish')
	author = models.ForeignKey(User, related_name = 'blog_posts')
	body = models.TextField()
	publish = models.DateTimeField(default = timezone.now)
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)
	status = models.CharField(max_length = 10, choices = STATUS_CHOICES, default = 'draft')

	objects = models.Manager()
	published = PublishManager() #Define customer manager
	#Only returns published

	#Add tags
	tags = TaggableManager()

	class Meta:
		ordering = ('-publish',) #Sort by publish descending

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		#create an url that uses blog:post_detail as display view and pass args to it.
		return reverse('blog:post_detail',args = [
			self.publish.year,
			self.publish.strftime("%m"),
			self.publish.strftime("%d"),
			self.slug
			])

class Comment(models.Model):
	# related_name specifices the name of the reverse relation from Post model back to this model
	# If you dont define the related_name attribute, Django will use comment_set.
	# So potentially you can do Post.comments
	post = models.ForeignKey(Post, related_name = "comments")
	name = models.CharField(max_length = 80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)
	active = models.BooleanField(default = True)

	class Meta:
		#sort by created
		ordering = ('created',)

	def __str__(self):
		return 'Comment by {} on {}'.format(self.name, self.post)

Django/Blog/Code/mysite/blog/forms.py
from django import forms
from .models import Comment
#create a form
class EmailPostForm(forms.Form):
	#fields in a form
	
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False,widget = forms.Textarea)

#it would be redundant to define the field types in your form
#because you’ve already defined the fields in your model.
#Django provides a helper class that lets you create a Form class from a Django model.
class CommentForm(forms.ModelForm):
	#The generated Form class will have a form field for every model field specified, in the order specified in the fields attribute.
	class Meta:
		model = Comment
		fields = ('name','email','body')

Django/Blog/Code/mysite/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count

# Create your views here.
def post_list(request, tag_slug = None):
	#created a view to display list of posts.
	object_list = Post.published.all()
	tag=None

	if tag_slug:
		#get the corresponding tag that's related to tag_slug
		tag = get_object_or_404(Tag,slug = tag_slug)
		#Get all objects with the tag (not tag_slug)
		object_list = object_list.filter(tags__in=[tag])

	paginator = Paginator(object_list, 3) #3 posts each page
	page = request.GET.get('page')

	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	#First para: request, 
	#Second para: which template in to use (template path (the path in templates))
	#Third para: parameter to pass to template as input
	return render(request, 'blog/post/list.html', {'posts':posts,'page':page, 'tag':tag})

# The parameters year, month, day, post are parsed in url when you type the url
# Define in urls.py
def post_detail(request, year, month, day, post):
	#created a view to display a single post
	post = get_object_or_404(Post, slug = post, status = 'published', publish__year = year, publish__month = month, publish__day = day)

	comments = post.comments.filter(active = True)

	is_new_comment = False

	if request.method == 'POST':

		comment_form = CommentForm(request.POST)

		if comment_form.is_valid():

			#Dont save now
			new_comment = comment_form.save(commit=False)

			new_comment.post = post

			new_comment.save()

			is_new_comment = True
	else:

		comment_form = CommentForm()

	# List of similar posts

	# Retrieve a list of ids for tags of current post. 
	# flag list like [1,2,3]
	post_tags_ids = post.tags.values_list('id', flat=True)
	print(post_tags_ids)
	#exclude the current post from all
	similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
	#Count same tags and order and get first 4.
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:1]
	print(similar_posts)

	return render(request, 'blog/post/detail.html',{'post':post,'comments':comments,'comment_form': comment_form,'new_comment':is_new_comment,'similar_posts':similar_posts})


def post_share(request, post_id):

	post = get_object_or_404(Post, id = post_id, status = "published")
	sent = False

	#The view is initially loaded with a post command
	if request.method == 'POST':
		#Create a form using submitted data from post
		form = EmailPostForm(request.POST)
		#valid data in form
		if form.is_valid():
			cd = form.cleaned_data #Return all valid fields as dict
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
			#Only by post a email will be sent.
			send_mail(subject, message, 'admin@myblog.com', [cd['to']])
			sent = True
	else:
		form = EmailPostForm()

	return render(request,'blog/post/share.html',{'post':post,'form':form,'sent':sent})

Django/Blog/Code/mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %} 
<!--load static file (css/images)-->
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div id="content">
        	{% block content %}
        	{% endblock %}
        </div>
        <div id="sidebar">
        	<h2>My blog</h2>
        	<p>This is my blog. I've Written {% total_posts %} posts so far</p>
            <h3>
            Latest Posts
            </h3>
            {% show_latest_posts %}

            <h3>
            Most commented posts
            </h3>
            {% get_most_commented_posts as most_commented_posts %}
            <ul>
            {% for post in most_commented_posts %}
                <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
            {% endfor %}
            </ul>
        </div>
    </body>
</html>

Django/Blog/Code/mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{post.title}}{% endblock %}

{% block content %}
	<h1>{{post.title}}</h1>
	<p class="date">Published {{post.publish}} by {{post.author}}
	</p>
	{{post.body|linebreaks}}
	<!-- create Url Link to view blog:post_share. Namespace blog, url name post_share (registered in urls.py).-->
	<p><a href="{% url 'blog:post_share' post.id %}">Share This Post</a></p>


	<h2>Similar posts</h2>
	{% for post in similar_posts %}
	<p><a href="{{ post.get_absolute_url }}">{{post.title}}</a></p>
	{% empty %}
	There are no similar posts yet.
	{% endfor%}



	{% with comments.count as total_comments%}
		<h2>
			{{total_comments}} comment{{total_comments|pluralize}}
		</h2>
	{% endwith%}

	{% for comment in comments %}
	<div class="comment">
		<p class="info">
		Comment {{forloop.counter}} by {{comment.name}} {{comment.created}}
		{{comment.body|markdown}}
		</p>
	</div>
	{% empty %}
	<p>No Comments Yet</p>
	{% endfor %}

	{% if new_comment %}
	<h2> Your comment has been added </h2>
	{% else %}
	<h2>Add a comment</h2>
	<form action="." method="post">
		{{comment_form.as_p}}
		{%csrf_token%}
		<p><input type="submit" value="Add Comment"></p>
	</form>
	{%endif%}
{% endblock %}

Django/Blog/Code/mysite/blog/templates/blog/post/latest_posts.html
<ul>

{% for post in latest_posts %}
	<li>
		<a href="{{post.get_absolute_url }}">{{post.title}}</a>
	</li>
{% endfor %}

</ul>

Django/Blog/Code/mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
<h1>
My Blog
</h1>

{% if tag %}
<h2>Posts tagged with "{{tag.name}}"</h2>
{% endif%}
{%for post in posts%}
	<h2>
		<!-- Auto url gen-->	
		<a href="{{post.get_absolute_url}}">{{post.title}}</a>
	</h2>
	<p class="tags">
		Tags:
		{%for tag in post.tags.all%}
			<a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a>
			{% if not forloop.last%}
			,
			{%endif%}
		{%endfor%}
	</p>
	<p class="date">Published {{post.publish}} by {{post.author}}
	</p>
	{{post.body|markdown|truncatewords_html:30}}
{%endfor%}

{%include "pagination.html" with page=posts%}

{% endblock %}

Django/Blog/Code/mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent by e-mail.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
        <!-- Form action is "." When reload this page it's not get anymore instead it is post, so an email will be sent-->
            {{ form.as_p }} <!--render form as paragraph, as_ul, as_table -->
            {% csrf_token %} <!--hidden field void attacks-->
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

Django/Blog/Code/mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>